name: Quality assurance

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  python-checks:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: true
        enable-cache: true
    - name: Install dependencies
      run: uv sync --extra all
    - name: Run Python checks toolchain
      run: make python-checks

  docs-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
          enable-cache: true
      - name: Install dependencies
        run: uv sync
      - name: Run docs checks toolchain
        run: make docs-checks
